CREATE TABLE email_deliveries (
    id BINARY(16) NOT NULL,
    actor_id BINARY(16) NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    template VARCHAR(128) NOT NULL,
    recipient_email VARCHAR(320) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body_text TEXT NOT NULL,
    status ENUM('queued','processing','sent','failed') NOT NULL DEFAULT 'queued',
    provider VARCHAR(64) NOT NULL DEFAULT '',
    provider_message_id VARCHAR(191) NOT NULL DEFAULT '',
    failure_code VARCHAR(128) NOT NULL DEFAULT '',
    last_error VARCHAR(1024) NOT NULL DEFAULT '',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    available_at TIMESTAMP(6) NOT NULL,
    worker_id VARCHAR(128) NULL,
    lease_expires_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    sent_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_email_deliveries_resource (resource_type,resource_id,created_at),
    KEY idx_email_deliveries_recipient (recipient_email,status,created_at),
    KEY idx_email_deliveries_claim (status,available_at,lease_expires_at),
    CONSTRAINT fk_email_deliveries_actor FOREIGN KEY (actor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
