CREATE TABLE skill_runs (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    skill_name VARCHAR(128) NOT NULL,
    skill_version VARCHAR(32) NOT NULL,
    status ENUM('waiting_confirmation','running','succeeded','failed','cancelled') NOT NULL,
    current_state VARCHAR(64) NOT NULL,
    risk_level ENUM('none','low','medium','high') NOT NULL,
    requires_confirmation BOOLEAN NOT NULL,
    input_json JSON NOT NULL,
    output_json JSON NULL,
    create_key VARCHAR(191) NOT NULL,
    confirmation_key VARCHAR(191) NULL,
    last_action VARCHAR(32) NOT NULL DEFAULT '',
    last_action_key VARCHAR(191) NULL,
    attempt SMALLINT UNSIGNED NOT NULL,
    max_steps SMALLINT UNSIGNED NOT NULL,
    timeout_ms INT UNSIGNED NOT NULL,
    max_input_bytes INT UNSIGNED NOT NULL,
    max_cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    error_code VARCHAR(128) NOT NULL DEFAULT '',
    error_message VARCHAR(1024) NOT NULL DEFAULT '',
    revision INT UNSIGNED NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_skill_runs_create (user_id,create_key),
    KEY idx_skill_runs_user_created (user_id,created_at),
    KEY idx_skill_runs_status_updated (status,updated_at),
    CONSTRAINT fk_skill_runs_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_run_action_keys (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    action VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_skill_run_action_keys_user (user_id,idempotency_key),
    KEY idx_skill_run_action_keys_run (run_id,created_at),
    CONSTRAINT fk_skill_run_action_keys_run FOREIGN KEY (run_id) REFERENCES skill_runs(id),
    CONSTRAINT fk_skill_run_action_keys_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_run_steps (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    sequence_no SMALLINT UNSIGNED NOT NULL,
    state VARCHAR(64) NOT NULL,
    status ENUM('succeeded','failed','cancelled') NOT NULL,
    tool_name VARCHAR(128) NOT NULL DEFAULT '',
    input_json JSON NULL,
    output_json JSON NULL,
    error_code VARCHAR(128) NOT NULL DEFAULT '',
    error_message VARCHAR(1024) NOT NULL DEFAULT '',
    started_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_skill_run_steps_sequence (run_id,sequence_no),
    CONSTRAINT fk_skill_run_steps_run FOREIGN KEY (run_id) REFERENCES skill_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tool_executions (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    risk_level ENUM('none','low','medium','high') NOT NULL,
    status ENUM('succeeded','failed','cancelled') NOT NULL,
    idempotency_key VARCHAR(191) NULL,
    input_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    output_json JSON NULL,
    error_code VARCHAR(128) NOT NULL DEFAULT '',
    error_message VARCHAR(1024) NOT NULL DEFAULT '',
    started_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_tool_executions_user_started (user_id,started_at),
    KEY idx_tool_executions_run (run_id,started_at),
    CONSTRAINT fk_tool_executions_run FOREIGN KEY (run_id) REFERENCES skill_runs(id),
    CONSTRAINT fk_tool_executions_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE generated_files (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    media_type VARCHAR(191) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    storage_key VARCHAR(1024) NOT NULL,
    status ENUM('active','deleted') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_generated_files_storage (storage_key(512)),
    KEY idx_generated_files_user_created (user_id,created_at),
    CONSTRAINT fk_generated_files_run FOREIGN KEY (run_id) REFERENCES skill_runs(id),
    CONSTRAINT fk_generated_files_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
