CREATE TABLE ledger_candidates (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    source_message_id BINARY(16) NULL,
    raw_text VARCHAR(2000) NOT NULL,
    direction ENUM('income','expense') NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NULL,
    amount_minor BIGINT UNSIGNED NULL,
    category VARCHAR(64) NOT NULL DEFAULT 'other',
    merchant VARCHAR(255) NOT NULL DEFAULT '',
    occurred_at TIMESTAMP(6) NULL,
    timezone VARCHAR(64) NOT NULL,
    time_precision ENUM('minute','part_of_day','date') NULL,
    confidence DECIMAL(5,4) NOT NULL,
    needs_clarification JSON NOT NULL,
    status ENUM('pending','needs_clarification','confirmed','expired','cancelled') NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_ledger_candidates_user_status (user_id,status,created_at),
    CONSTRAINT fk_ledger_candidates_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ledger_candidates_message FOREIGN KEY (source_message_id) REFERENCES messages(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ledger_entries (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    candidate_id BINARY(16) NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    direction ENUM('income','expense') NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    amount_minor BIGINT UNSIGNED NOT NULL,
    category VARCHAR(64) NOT NULL,
    merchant VARCHAR(255) NOT NULL DEFAULT '',
    occurred_at TIMESTAMP(6) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    note VARCHAR(1000) NOT NULL DEFAULT '',
    status ENUM('active','deleted') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ledger_entries_user_idempotency (user_id,idempotency_key),
    UNIQUE KEY uk_ledger_entries_candidate (candidate_id),
    KEY idx_ledger_entries_user_occurred (user_id,status,occurred_at),
    KEY idx_ledger_entries_user_category (user_id,status,category,occurred_at),
    CONSTRAINT fk_ledger_entries_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ledger_entries_candidate FOREIGN KEY (candidate_id) REFERENCES ledger_candidates(id),
    CONSTRAINT chk_ledger_entries_amount CHECK (amount_minor > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ledger_exports (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    month CHAR(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    status ENUM('queued','processing','completed','failed','expired') NOT NULL,
    storage_key VARCHAR(1024) NULL,
    sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    size_bytes BIGINT UNSIGNED NULL,
    failure_code VARCHAR(128) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_ledger_exports_user_created (user_id,created_at),
    CONSTRAINT fk_ledger_exports_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
