CREATE TABLE long_term_memories (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    memory_type ENUM('preference','relationship','goal','commitment','experience','fact') NOT NULL,
    content VARCHAR(2000) NOT NULL,
    normalized_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_conversation_id BINARY(16) NULL,
    source_message_id BINARY(16) NULL,
    confidence DECIMAL(5,4) NOT NULL,
    importance DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    sensitivity ENUM('normal','personal','sensitive') NOT NULL DEFAULT 'normal',
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    status ENUM('active','deleted','superseded') NOT NULL DEFAULT 'active',
    valid_from TIMESTAMP(6) NOT NULL,
    valid_to TIMESTAMP(6) NULL,
    supersedes_id BINARY(16) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_memories_user_status (user_id,status,pinned,updated_at),
    KEY idx_memories_user_hash (user_id,normalized_hash,status),
    CONSTRAINT fk_memories_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_memories_conversation FOREIGN KEY (source_conversation_id) REFERENCES conversations(id),
    CONSTRAINT fk_memories_message FOREIGN KEY (source_message_id) REFERENCES messages(id),
    CONSTRAINT fk_memories_supersedes FOREIGN KEY (supersedes_id) REFERENCES long_term_memories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
